spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: customer-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/customers/**
          - id: fraud-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/fraud/**
management:
  endpoints:
    web.exposure.include: health,info,prometheus