spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: customer-service
            uri: ${CUSTOMER_SERVICE_URI:http://localhost:8081}
            predicates:
              - Path=/api/v1/customers/**
          - id: fraud-service
            uri: ${FRAUD_SERVICE_URI:http://localhost:8082}
            predicates:
              - Path=/api/v1/fraud/**
management:
  endpoints:
    web.exposure.include: health,info,prometheus